const category = [
    {
        "id": 1,
        "name": "Lan Hoàng Thảo",
        "image": "https://drive.google.com/thumbnail?id=1XYc7_pglD5Sz8vQrXoNmGOduKMAgV_qr"
    },
    {
        "id": 2,
        "name": "Lan Hồ Điệp",
        "image": "https://drive.google.com/thumbnail?id=1XcGdQaJv36UsbChBrV7q91BBU4veA2JU"
    },
    {
        "id": 3,
        "name": "Lan Kiếm",
        "image": "https://drive.google.com/thumbnail?id=1c8-6sZcyASjycPweTVdUHsH79FQOyabn"
    },
    {
        "id": 4,
        "name": "Lan Ngọc Điểm",
        "image": "https://drive.google.com/thumbnail?id=1ZBnsxyNPmoDVWjJ2EsDYJsw8J9vcSbeN"
    },
    {
        "id": 5,
        "name": "Lan Vũ Nữ",
        "image": "https://drive.google.com/thumbnail?id=1xdrrzAeNASY_ReWOECwge2rny2AMriO6"
    },
]
const orchid = [
    {
        "id": 1,
        "name": "Lan Phi Điệp",
        "image": "https://drive.google.com/thumbnail?id=1-XpMHlHDolUGlITvTOTY1DQQ91wwP_Lr",
        "categoryId": 1,
        "minHeight": 50,
        "maxHeight": 100,
        "minTemperature": 20,
        "maxTemperature": 27,
        "minHumidity": 50,
        "maxHumidity": 80,
        "description": "Lan phi điệp là một trong những loài lan phổ biến và được yêu thích nhất trong việc trồng lan cảnh. Lan này có nguồn gốc từ vùng nhiệt đới châu Á. Lan phi điệp có hoa lớn, màu sắc đa dạng và thường nở quanh năm. Chúng thích hợp cho việc trồng trong nhà và dễ bảo quản."
    },
    {
        "id": 2,
        "name": "Lan Trầm",
        "image": "https://drive.google.com/thumbnail?id=1gye3GP0BdpOdbiaP6eL1vpcgz5nxLraO",
        "categoryId": 1,
        "minHeight": 30,
        "maxHeight": 60,
        "minTemperature": 18,
        "maxTemperature": 25,
        "minHumidity": 50,
        "maxHumidity": 80,
        "description": "Lan trầm là một trong những loài lan có hương thơm quyến rũ. Chúng thường được trồng ở vùng nhiệt đới và có thể nở hoa mùa xuân hoặc mùa hạ. Lan trầm có nhiều màu sắc khác nhau và là một lựa chọn phổ biến cho việc trang trí nội thất."
    },
    {
        "id": 3,
        "name": "Hoàng Thảo Kèn",
        "image": "https://drive.google.com/thumbnail?id=1Y0VTJ-aQFXJnCNToTbmf-Tarjz87V1Oo",
        "categoryId": 1,
        "minHeight": 40,
        "maxHeight": 80,
        "minTemperature": 20,
        "maxTemperature": 28,
        "minHumidity": 60,
        "maxHumidity": 90,
        "description": "Hoàng thảo kèn là một trong những loài hoa lan lâu đời và phổ biến nhất trong giới chơi lan. Chúng có hoa lớn, màu sắc rực rỡ và hương thơm quyến rũ. Hoàng thảo kèn được coi là biểu tượng của sự quý phái và đẳng cấp."
    },
    {
        "id": 4,
        "name": "Kiều",
        "image": "https://drive.google.com/thumbnail?id=1CLHvg8-V1cgQB41smKzt7nfv-G_2ZJFd",
        "categoryId": 1,
        "minHeight": 20,
        "maxHeight": 40,
        "minTemperature": 15,
        "maxTemperature": 25,
        "minHumidity": 40,
        "maxHumidity": 70,
        "description": "Kiều là một loài lan có hoa nhỏ và tương đối dễ trồng. Chúng thường nở hoa vào mùa xuân và mùa hạ, mang lại sự tươi mới cho không gian trồng lan. Kiều có màu sắc đa dạng và là một trong những loài lan phổ biến trong việc trang trí nhà cửa."
    },
    {
        "id": 5,
        "name": "Hoàng Lạp",
        "image": "https://drive.google.com/thumbnail?id=1fWMjxDtb-qb6oBCh0hBtzUvbHp7sbD0I",
        "categoryId": 1,
        "minHeight": 40,
        "maxHeight": 80,
        "minTemperature": 18,
        "maxTemperature": 26,
        "minHumidity": 60,
        "maxHumidity": 85,
        "description": "Hoàng lạp là một loài lan có nguồn gốc từ vùng nhiệt đới của châu Mỹ. Chúng có hoa nhỏ, màu sắc đa dạng và thường nở vào ban đêm, phát huy hương thơm mạnh mẽ để thu hút côn trùng hạt phấn."
    },
    {
        "id": 6,
        "name": "Hạc Vỹ",
        "image": "https://drive.google.com/thumbnail?id=1-dZ2r0MQDyq-oKzzCpaH3JBKsnEr_Y-9",
        "categoryId": 1,
        "minHeight": 60,
        "maxHeight": 100,
        "minTemperature": 15,
        "maxTemperature": 25,
        "minHumidity": 60,
        "maxHumidity": 80,
        "description": "Hạc vỹ là một trong những loài lan có hoa lớn và thường được trồng ngoài trời. Chúng thích hợp cho các khu vườn và sân thượng. Hạc vỹ có thể chịu được điều kiện khí hậu khắc nghiệt và thường nở hoa vào mùa xuân."
    },
    {
        "id": 7,
        "name": "Hoàng Thảo Hoa Vàng",
        "image": "https://drive.google.com/thumbnail?id=1Y3MMcdTKsprdFmY-ALuyekT4L7WTLBjD",
        "categoryId": 1,
        "minHeight": 30,
        "maxHeight": 60,
        "minTemperature": 20,
        "maxTemperature": 28,
        "minHumidity": 50,
        "maxHumidity": 80,
        "description": "Hoàng thảo hoa vàng là một loài lan có hoa nhỏ và rất dễ trồng. Chúng thường được trồng trong các chậu nhỏ và có thể nở hoa quanh năm. Hoàng thảo hoa vàng có màu sắc tươi sáng và làm cho không gian trồng lan trở nên sống động."
    },
    {
        "id": 8,
        "name": "Hồ Điệp Thường",
        "image": "https://drive.google.com/thumbnail?id=1TaL638_4WXaOMXyUAVOI1LkRsj2EMTo1",
        "categoryId": 2,
        "minHeight": 20,
        "maxHeight": 50,
        "minTemperature": 18,
        "maxTemperature": 25,
        "minHumidity": 60,
        "maxHumidity": 80,
        "description": "Lan Hồ Điệp Thường là một loại lan hồ điệp phổ biến với hình dáng độc đáo của hoa. Chúng thường mọc trên các thân cây mạnh mẽ và có lá lá dày. Hoa của Lan Hồ Điệp Thường có hình dáng và màu sắc đặc trưng, làm cho chúng trở thành điểm nhấn thu hút sự chú ý trong vườn lan."
    },
    {
        "id": 9,
        "name": "Tiểu Lan Hồ Điệp",
        "image": "https://drive.google.com/thumbnail?id=1Bz-wL7yVRV9Ah104wCde8x1oSz8jqctV",
        "categoryId": 2,
        "minHeight": 15,
        "maxHeight": 30,
        "minTemperature": 20,
        "maxTemperature": 28,
        "minHumidity": 50,
        "maxHumidity": 80,
        "description": "Tiểu Lan Hồ Điệp là một loại lan hồ điệp có hình dáng và màu sắc độc đáo. Chúng thường được tìm thấy ở vùng nhiệt đới và có thể trồng thành công trong môi trường nhà kính. Hoa của Tiểu Lan Hồ Điệp thường có hình dáng đẹp và màu sắc rực rỡ, làm cho chúng được ưa chuộng trong việc trang trí nội thất."
    },
    {
        "id": 10,
        "name": "Mãn Thiên",
        "image": "https://drive.google.com/thumbnail?id=1CWfIdaBDVshOf6PmA4BO2IVKnAXu5ktS",
        "categoryId": 2,
        "minHeight": 40,
        "maxHeight": 80,
        "minTemperature": 22,
        "maxTemperature": 30,
        "minHumidity": 70,
        "maxHumidity": 90,
        "description": "Mãn Thiên là một loại lan hồ điệp có hình dáng độc đáo và màu sắc thu hút. Chúng thường mọc trên các thân cây mạnh mẽ và có lá lá dày. Hoa của Lan Hồ Điệp Mãn Thiên có hình dáng và màu sắc đặc trưng, làm cho chúng trở thành điểm nhấn thu hút sự chú ý trong vườn lan."
    },
    {
        "id": 11,
        "name": "Lan Kiếm Lô Hội",
        "image": "https://drive.google.com/thumbnail?id=1jP9s5vG00LzoCfhxd4JA1-omu3kuXOxJ",
        "categoryId": 3,
        "minHeight": 40,
        "maxHeight": 80,
        "minTemperature": 20,
        "maxTemperature": 30,
        "minHumidity": 60,
        "maxHumidity": 80,
        "description": "Lan Kiếm Lô Hội là một loại lan kiếm phổ biến với hoa lớn, màu sắc rực rỡ và hương thơm quyến rũ. Chúng thường được trồng trong các khu vườn hoặc sân vườn và có thể chịu được điều kiện khí hậu khắc nghiệt."
    },
    {
        "id": 12,
        "name": "Lan Kiếm Tiên Vũ",
        "image": "https://drive.google.com/thumbnail?id=1JeN8KQ-WtaW5KmAniygLjZKyZmN7XRop",
        "categoryId": 3,
        "minHeight": 30,
        "maxHeight": 60,
        "minTemperature": 18,
        "maxTemperature": 25,
        "minHumidity": 50,
        "maxHumidity": 80,
        "description": "Lan Kiếm Tiên Vũ là một trong những loại lan kiếm phổ biến, có hoa nhỏ và hình dáng độc đáo. Chúng thường được trồng trong chậu nhỏ và là một lựa chọn phổ biến cho việc trang trí nội thất."
    },
    {
        "id": 13,
        "name": "Lan Kiếm Hai Màu",
        "image": "https://drive.google.com/thumbnail?id=1WcYGEAvag4N6KJyecfQQlInZ1YbjMNuA",
        "categoryId": 3,
        "minHeight": 20,
        "maxHeight": 40,
        "minTemperature": 15,
        "maxTemperature": 25,
        "minHumidity": 40,
        "maxHumidity": 70,
        "description": "Lan Kiếm Hai Màu là một loại lan kiếm phổ biến với hoa nhỏ và màu sắc đa dạng. Chúng thích hợp cho việc trồng trong chậu nhỏ hoặc treo lơ lửng, tạo điểm nhấn cho không gian trồng lan."
    },
    {
        "id": 14,
        "name": "Lan Kiếm Dừa",
        "image": "https://drive.google.com/thumbnail?id=1XtkEkaTkbXA5CrKNsMk4tZelc7l41iHd",
        "categoryId": 3,
        "minHeight": 50,
        "maxHeight": 100,
        "minTemperature": 20,
        "maxTemperature": 30,
        "minHumidity": 60,
        "maxHumidity": 80,
        "description": "Lan Kiếm Dừa là một loại lan kiếm phổ biến với hoa lớn, màu sắc đa dạng và hương thơm quyến rũ. Chúng thường được trồng treo lơ lửng và làm điểm nhấn cho không gian trồng lan."
    },
    {
        "id": 15,
        "name": "Lan Ngọc Điểm Rừng",
        "image": "https://drive.google.com/thumbnail?id=1yfD_KmrzKLdlqADrr8W-_yEnlspYHeLd",
        "categoryId": 3,
        "minHeight": 40,
        "maxHeight": 80,
        "minTemperature": 22,
        "maxTemperature": 30,
        "minHumidity": 70,
        "maxHumidity": 90,
        "description": "Lan Ngọc Điểm Rừng là một loại lan phổ biến được tìm thấy ở các khu rừng nhiệt đới. Chúng có hoa nhỏ và màu sắc đẹp, thích hợp cho việc trang trí nội thất và sân vườn. Lan Ngọc Điểm Rừng cần môi trường ẩm ướt và ánh sáng phù hợp để phát triển tốt."
    },
    {
        "id": 16,
        "name": "Lan Ngọc Điểm Thái",
        "image": "https://drive.google.com/thumbnail?id=1mjB6CZy4UIQ5u1XAaaHBlve4lDTanx8C",
        "categoryId": 3,
        "minHeight": 35,
        "maxHeight": 70,
        "minTemperature": 20,
        "maxTemperature": 28,
        "minHumidity": 60,
        "maxHumidity": 85,
        "description": "Lan Ngọc Điểm Thái là một loại lan kiếm có hoa lớn và màu sắc đẹp. Chúng thường được trồng trong các chậu lớn hoặc trên vườn lan. Lan Ngọc Điểm Thái cần đất cây giàu dinh dưỡng và độ ẩm cao để phát triển tốt."
    },
    {
        "id": 17,
        "name": "Lan Vũ Nữ Bút Chì",
        "image": "https://drive.google.com/thumbnail?id=1sMRgWOuj2avPARa3ViG8wNQh-kfKU_cg",
        "categoryId": 5,
        "minHeight": 20,
        "maxHeight": 40,
        "minTemperature": 18,
        "maxTemperature": 25,
        "minHumidity": 60,
        "maxHumidity": 80,
        "description": "Lan Vũ Nữ Bút Chì là một loại lan vũ nữ phổ biến với hoa đẹp và màu sắc đa dạng. Chúng thích hợp cho việc trồng trong nhà hoặc ngoài trời với điều kiện ánh sáng phù hợp. Lan Vũ Nữ Bút Chì cần độ ẩm và nhiệt độ ổn định để phát triển và nở hoa đẹp."
    },
    {
        "id": 18,
        "name": "Lan Vũ Nữ Peru",
        "image": "https://drive.google.com/thumbnail?id=186GF2jlsAvP24DPJr1kpR2CDiAz1VNbR",
        "categoryId": 5,
        "minHeight": 25,
        "maxHeight": 50,
        "minTemperature": 20,
        "maxTemperature": 28,
        "minHumidity": 50,
        "maxHumidity": 80,
        "description": "Lan Vũ Nữ Peru là một loại lan vũ nữ được ưa chuộng với hoa lớn và màu sắc rực rỡ. Chúng thường được trồng trong các chậu lớn hoặc trên vườn lan. Lan Vũ Nữ Peru cần đất cây giàu dinh dưỡng và độ ẩm cao để phát triển tốt."
    },
    {
        "id": 19,
        "name": "Lan Vũ Nữ Tai Thỏ",
        "image": "https://drive.google.com/thumbnail?id=11oukqZi5VCqKOUWvdrEeW5RCZnDkLZxV",
        "categoryId": 5,
        "minHeight": 30,
        "maxHeight": 60,
        "minTemperature": 22,
        "maxTemperature": 30,
        "minHumidity": 60,
        "maxHumidity": 85,
        "description": "Lan Vũ Nữ Tai Thỏ là một loại lan vũ nữ phổ biến với hoa lớn và màu sắc đa dạng. Chúng thích hợp cho việc trồng trong nhà hoặc ngoài trời với điều kiện ánh sáng phù hợp. Lan Vũ Nữ Tai Thỏ cần độ ẩm và nhiệt độ ổn định để phát triển và nở hoa đẹp."
    },
    {
        "id": 20,
        "name": "Lan Vũ Nữ Mật Ngọt",
        "image": "https://drive.google.com/thumbnail?id=1bdEtfqsiTRaVSV5Z6PJGIXj5jz07_bS4",
        "categoryId": 5,
        "minHeight": 25,
        "maxHeight": 50,
        "minTemperature": 20,
        "maxTemperature": 28,
        "minHumidity": 50,
        "maxHumidity": 80,
        "description": "Lan Vũ Nữ Mật Ngọt là một loại lan vũ nữ được ưa chuộng với hoa lớn và màu sắc rực rỡ. Chúng thường được trồng trong các chậu lớn hoặc trên vườn lan. Lan Vũ Nữ Mật Ngọt cần đất cây giàu dinh dưỡng và độ ẩm cao để phát triển tốt."
    },
    {
        "id": 21,
        "name": "Lan Vũ Nữ Nhện Đỏ",
        "image": "https://drive.google.com/thumbnail?id=1huJMhmncZycbnCbLzKtML9GTk620Ud75",
        "categoryId": 5,
        "minHeight": 30,
        "maxHeight": 60,
        "minTemperature": 22,
        "maxTemperature": 30,
        "minHumidity": 60,
        "maxHumidity": 85,
        "description": "Lan Vũ Nữ Nhện Đỏ là một loại lan vũ nữ phổ biến với hoa lớn và hình dáng độc đáo giống như nhện. Chúng thích hợp cho việc trồng trong nhà hoặc ngoài trời với điều kiện ánh sáng phù hợp. Lan Vũ Nữ Nhện Đỏ cần độ ẩm và nhiệt độ ổn định để phát triển và nở hoa đẹp."
    }
]